"use client";
import { FormEvent, useEffect, useState } from "react";
import { Button, Field, Badge } from "@/components/ui";

type StatusState = {
  kind: "idle" | "busy" | "ok" | "error";
  text: string;
};

function Status({state}:{state:{kind:"idle"|"busy"|"ok"|"error";text:string}}){if(state.kind==="idle")return null;return <div className={`callout ${state.kind==="error"?"warning":""}`} style={{marginTop:12}}>{state.kind==="busy"?"Memproses…":state.text}</div>}
async function jsonPost(url:string,payload:unknown){const r=await fetch(url,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Request gagal");return d;}

export function OfficeForm(){const [s,setS]=useState({kind:"idle" as const,text:""});async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setS({kind:"busy",text:""});try{await jsonPost("/api/admin/offices",{name:f.get("name"),address:f.get("address"),latitude:f.get("latitude"),longitude:f.get("longitude"),radius:f.get("radius"),maxAccuracy:f.get("accuracy"),timezone:f.get("timezone")});setS({kind:"ok",text:"Office tersimpan. Muat ulang halaman untuk melihat data terbaru."});}catch(x){setS({kind:"error",text:x instanceof Error?x.message:"Gagal"});}}
return <form onSubmit={submit} className="formgrid"><Field label="Nama office"><input name="name" className="input" defaultValue="Solo HQ" required/></Field><Field label="Alamat"><input name="address" className="input" placeholder="Surakarta"/></Field><Field label="Latitude"><input name="latitude" className="input" defaultValue="-7.566600" required/></Field><Field label="Longitude"><input name="longitude" className="input" defaultValue="110.816700" required/></Field><Field label="Radius (meter)"><input name="radius" className="input" type="number" min="10" defaultValue="50" required/></Field><Field label="Max accuracy"><input name="accuracy" className="input" type="number" min="5" defaultValue="30" required/></Field><Field label="Timezone" full><input name="timezone" className="input" defaultValue="Asia/Jakarta" required/></Field><div className="field full"><Button variant="primary" type="submit">Simpan office</Button><Status state={s}/></div></form>}

export function InviteEmployeeForm(){const [s,setS]=useState({kind:"idle" as const,text:""});async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setS({kind:"busy",text:""});try{await jsonPost("/api/admin/invite",{email:f.get("email"),fullName:f.get("fullName"),employeeNumber:f.get("employeeNumber"),role:f.get("role")});setS({kind:"ok",text:"Undangan dibuat. Supabase akan menangani email invite sesuai konfigurasi Auth."});e.currentTarget.reset();}catch(x){setS({kind:"error",text:x instanceof Error?x.message:"Gagal"});}}
return <form onSubmit={submit} className="formgrid"><Field label="Nama"><input name="fullName" className="input" required/></Field><Field label="Email"><input name="email" type="email" className="input" required/></Field><Field label="Nomor karyawan"><input name="employeeNumber" className="input" placeholder="EMP-0012"/></Field><Field label="Role"><select name="role" className="select" defaultValue="employee"><option value="employee">Employee</option><option value="supervisor">Supervisor</option><option value="manager">Manager</option><option value="hr">HR</option></select></Field><div className="field full"><Button variant="primary" type="submit">Kirim undangan</Button><Status state={s}/></div></form>}

export function AnnouncementForm(){const [s,setS]=useState({kind:"idle" as const,text:""});async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setS({kind:"busy",text:""});try{await jsonPost("/api/admin/announcements",{title:f.get("title"),body:f.get("body"),target:{type:f.get("target")},requireAck:f.get("ack")==="yes"});setS({kind:"ok",text:"Pengumuman dipublikasikan."});e.currentTarget.reset();}catch(x){setS({kind:"error",text:x instanceof Error?x.message:"Gagal"});}}
return <form onSubmit={submit} className="formgrid"><Field label="Judul" full><input name="title" className="input" required placeholder="Judul pengumuman"/></Field><Field label="Target"><select name="target" className="select"><option value="all">Semua karyawan</option><option value="office">Office</option><option value="department">Department</option></select></Field><Field label="Acknowledgement"><select name="ack" className="select"><option value="yes">Required</option><option value="no">Optional</option></select></Field><Field label="Isi" full><textarea name="body" className="textarea" required placeholder="Tulis dengan singkat dan jelas…"/></Field><div className="field full"><Button variant="primary" type="submit">Publish</Button><Status state={s}/></div></form>}

export function CreateCompanyForm(){const [s,setS]=useState({kind:"idle" as const,text:""});async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setS({kind:"busy",text:""});try{const d=await jsonPost("/api/platform/companies",{name:f.get("name"),slug:f.get("slug"),timezone:f.get("timezone"),plan:f.get("plan")});setS({kind:"ok",text:`Workspace dibuat: ${d.id||"success"}`});}catch(x){setS({kind:"error",text:x instanceof Error?x.message:"Gagal"});}}
return <form onSubmit={submit} className="formgrid"><Field label="Nama perusahaan"><input name="name" className="input" required/></Field><Field label="Slug"><input name="slug" className="input" required placeholder="pt-maju-jaya"/></Field><Field label="Timezone"><input name="timezone" className="input" defaultValue="Asia/Jakarta" required/></Field><Field label="Plan"><select name="plan" className="select"><option value="starter">Starter</option><option value="business">Business</option><option value="enterprise">Enterprise</option></select></Field><div className="field full"><Button variant="primary" type="submit">Create workspace</Button><Status state={s}/></div></form>}

export function ApiHint({children}:{children:React.ReactNode}){return <div style={{marginTop:12}}><Badge tone="info">Live API</Badge><span className="muted small" style={{marginLeft:8}}>{children}</span></div>}


type Option={id:string;label:string};
export function ScheduleAssignmentForm(){
  const [employees,setEmployees]=useState<Option[]>([]),[shifts,setShifts]=useState<Option[]>([]),[offices,setOffices]=useState<Option[]>([]),[state,setState]=useState({kind:"idle" as "idle"|"busy"|"ok"|"error",text:""});
  useEffect(()=>{Promise.all([fetch("/api/admin/employees").then(r=>r.json()),fetch("/api/admin/shifts").then(r=>r.json()),fetch("/api/admin/offices").then(r=>r.json())]).then(([e,s,o])=>{setEmployees((e.items||[]).map((x:{id:string;full_name:string})=>({id:x.id,label:x.full_name})));setShifts((s.items||[]).map((x:{id:string;name:string})=>({id:x.id,label:x.name})));setOffices((o.items||[]).map((x:{id:string;name:string})=>({id:x.id,label:x.name})));}).catch(()=>{});},[]);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setState({kind:"busy",text:""});try{await jsonPost("/api/admin/schedules",{employeeId:f.get("employeeId"),shiftId:f.get("shiftId")||null,officeId:f.get("officeId")||null,workDate:f.get("workDate"),workMode:f.get("workMode"),note:f.get("note")});setState({kind:"ok",text:"Schedule tersimpan."});}catch(x){setState({kind:"error",text:x instanceof Error?x.message:"Gagal"});}}
  return <form className="formgrid" onSubmit={submit}><Field label="Employee"><select name="employeeId" className="select" required><option value="">Pilih…</option>{employees.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></Field><Field label="Tanggal"><input name="workDate" className="input" type="date" required/></Field><Field label="Work mode"><select name="workMode" className="select"><option value="office">Office</option><option value="wfh">WFH</option><option value="field">Field</option><option value="business_trip">Business trip</option><option value="off">Off</option></select></Field><Field label="Shift"><select name="shiftId" className="select"><option value="">Tanpa shift</option>{shifts.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></Field><Field label="Office"><select name="officeId" className="select"><option value="">Default eligible office</option>{offices.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></Field><Field label="Catatan"><input name="note" className="input"/></Field><div className="field full"><Button variant="primary" type="submit">Assign schedule</Button><Status state={state}/></div></form>
}
