"use client";
import { useEffect, useRef, useState } from "react";
import { Button, Badge } from "@/components/ui";
import { Icon } from "@/components/icon";
import { GeofenceMap } from "@/components/geofence-map";

type Geo = { latitude:number; longitude:number; accuracy:number };
type Office = { id:string; name:string; latitude:number; longitude:number; radius:number; maxAccuracy:number; timezone:string };
const DEMO_OFFICE: Office = { id:"demo", name:"Solo HQ", latitude:-7.5666, longitude:110.8167, radius:50, maxAccuracy:30, timezone:"Asia/Jakarta" };

function distanceMeters(a:Geo,b:{latitude:number;longitude:number}){
  const R=6371e3, p1=a.latitude*Math.PI/180,p2=b.latitude*Math.PI/180, dp=(b.latitude-a.latitude)*Math.PI/180,dl=(b.longitude-a.longitude)*Math.PI/180;
  const x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2; return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));
}

export function AttendanceFlow(){
  const [step,setStep]=useState(0); const [geo,setGeo]=useState<Geo|null>(null); const [distance,setDistance]=useState<number|null>(null); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const [photo,setPhoto]=useState<string|null>(null); const [challenge,setChallenge]=useState("Tatap kamera selama 2 detik"); const [challengeToken,setChallengeToken]=useState<string|null>(null);
  const [office,setOffice]=useState<Office>(DEMO_OFFICE); const [workMode,setWorkMode]=useState("office");
  const video=useRef<HTMLVideoElement>(null); const stream=useRef<MediaStream|null>(null);
  const demo = process.env.NEXT_PUBLIC_DEMO_MODE === "true";

  async function ensureChallenge(){ if(challengeToken) return challengeToken; const res=await fetch('/api/attendance/challenge',{method:'POST'}); const data=await res.json(); if(!res.ok) throw new Error(data.error||'Gagal membuat attendance challenge'); setChallenge(data.challenge); setChallengeToken(data.token); return data.token as string; }
  async function locate(simulate=false){ setMessage(""); setBusy(true); try { await ensureChallenge(); } catch(e){ setMessage(e instanceof Error?e.message:'Challenge gagal'); setBusy(false); return; } if(simulate){ const g={latitude:office.latitude+0.00012,longitude:office.longitude+0.00008,accuracy:7}; setGeo(g);setDistance(distanceMeters(g,office));setStep(1);setBusy(false);return; }
    if(!navigator.geolocation){setMessage("Browser tidak mendukung geolocation.");setBusy(false);return;}
    navigator.geolocation.getCurrentPosition(pos=>{const g={latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy:pos.coords.accuracy};setGeo(g);setDistance(distanceMeters(g,office));setStep(1);setBusy(false);},err=>{setMessage(err.message);setBusy(false);},{enableHighAccuracy:true,maximumAge:0,timeout:12000});
  }
  async function startCamera(){ setMessage(""); try{ stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:720}},audio:false}); setStep(2); setTimeout(()=>{if(video.current&&stream.current) video.current.srcObject=stream.current;},50);}catch(e){setMessage(e instanceof Error?e.message:"Kamera tidak dapat diakses");}}
  function capture(){ const v=video.current;if(!v)return; const c=document.createElement("canvas"); const max=640, ratio=Math.min(1,max/v.videoWidth);c.width=Math.max(1,Math.round(v.videoWidth*ratio));c.height=Math.max(1,Math.round(v.videoHeight*ratio));const x=c.getContext("2d");x?.drawImage(v,0,0,c.width,c.height);setPhoto(c.toDataURL("image/jpeg",.72));stream.current?.getTracks().forEach(t=>t.stop());setStep(3); }
  function deviceToken(){let token=localStorage.getItem("nadi_device_token");if(!token){token=crypto.randomUUID()+crypto.randomUUID();localStorage.setItem("nadi_device_token",token);}return token;}
  async function submit(){ if(!geo||!photo)return;setBusy(true);setMessage("");try{const res=await fetch("/api/attendance/submit",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({eventType:"check_in",location:geo,clientDistance:distance,selfie:photo,challengeToken,challengeAcknowledged:true,deviceToken:deviceToken(),devicePlatform:navigator.userAgent})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Absensi ditolak");setStep(4);setMessage(data.message||"Absensi berhasil");}catch(e){setMessage(e instanceof Error?e.message:"Absensi gagal");setChallengeToken(null);setStep(0);}finally{setBusy(false);}}
  useEffect(()=>{ fetch("/api/attendance/context").then(r=>r.json()).then(data=>{ if(data?.office) setOffice(data.office); if(data?.workMode) setWorkMode(data.workMode); }).catch(()=>{}); return ()=>stream.current?.getTracks().forEach(t=>t.stop()); },[]);

  return <div className="grid two">
    <section className="card cardpad">
      <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10}}><div><div className="tiny muted">CHECK-IN · {office.name}</div><h2 style={{margin:"5px 0 0",fontSize:20,letterSpacing:"-.03em"}}>Verifikasi kehadiran</h2></div><Badge tone={step===4?"success":"info"}>{step===4?"Selesai":`Langkah ${Math.min(step+1,4)}/4`}</Badge></div>
      <div className="splitline"/>
      {step===0&&<div><div className="doticon" style={{width:48,height:48}}><Icon name="location" size={22}/></div><h3>Pastikan posisi Anda</h3><p className="muted small" style={{lineHeight:1.7}}>Lokasi dibaca langsung dari browser. Server tetap menghitung ulang jarak terhadap titik kantor dan menilai akurasi GPS.</p><div className="actions"><Button variant="primary" icon="location" onClick={()=>locate(false)} disabled={busy}>{busy?"Mencari lokasi…":"Ambil lokasi sekarang"}</Button>{demo&&<Button onClick={()=>locate(true)}>Simulasi dekat kantor</Button>}</div></div>}
      {step===1&&geo&&<div><div className="grid three"><div><div className="tiny muted">Jarak preview</div><strong style={{fontSize:22}}>{distance?.toFixed(1)} m</strong></div><div><div className="tiny muted">Akurasi</div><strong style={{fontSize:22}}>±{Math.round(geo.accuracy)} m</strong></div><div><div className="tiny muted">Radius policy</div><strong style={{fontSize:22}}>{office.radius} m</strong></div></div><div className="splitline"/><div className={`callout ${(distance||999)>office.radius||geo.accuracy>office.maxAccuracy?"warning":""}`}>{(distance||999)<=office.radius&&geo.accuracy<=office.maxAccuracy?"Lokasi terlihat layak. Validasi final tetap dilakukan server.":"Lokasi preview belum memenuhi policy. Ambil ulang lokasi atau pindah ke area kantor."}</div><div className="actions" style={{marginTop:14}}><Button onClick={()=>locate(false)}>Ambil ulang</Button><Button variant="primary" icon="camera" onClick={startCamera}>Lanjut verifikasi wajah</Button></div></div>}
      {step===2&&<div><div style={{position:"relative",overflow:"hidden",borderRadius:16,background:"#101512",aspectRatio:"4 / 3"}}><video ref={video} autoPlay playsInline muted style={{width:"100%",height:"100%",objectFit:"cover",transform:"scaleX(-1)"}}/><div style={{position:"absolute",inset:"16% 25%",border:"2px solid rgba(217,242,95,.8)",borderRadius:"46%"}}/></div><div className="callout" style={{marginTop:12}}><strong>Challenge:</strong> {challenge}. Pastikan hanya satu wajah terlihat dan pencahayaan cukup.</div><div className="actions" style={{marginTop:12}}><Button variant="primary" icon="camera" onClick={capture}>Ambil evidence</Button></div></div>}
      {step===3&&photo&&<div><div style={{display:"grid",gridTemplateColumns:"140px 1fr",gap:16,alignItems:"center"}}><img alt="Selfie evidence" src={photo} style={{width:140,height:140,objectFit:"cover",borderRadius:18,transform:"scaleX(-1)"}}/><div><Badge tone="success">Evidence ready</Badge><h3 style={{marginBottom:5}}>Kirim untuk validasi server</h3><p className="muted small" style={{lineHeight:1.6}}>Foto, lokasi, akurasi, challenge dan waktu akan dicatat. Mode produksi sebaiknya menghubungkan provider face/liveness pada adapter server.</p></div></div><div className="actions" style={{marginTop:16}}><Button onClick={startCamera}>Foto ulang</Button><Button variant="primary" icon="check" onClick={submit} disabled={busy}>{busy?"Memvalidasi…":"Kirim absensi"}</Button></div></div>}
      {step===4&&<div style={{textAlign:"center",padding:"25px 10px"}}><div className="doticon" style={{width:58,height:58,margin:"0 auto 14px",background:"#e9f7ef",color:"var(--success)"}}><Icon name="check" size={28}/></div><h2 style={{fontSize:24,margin:"0 0 7px"}}>Check-in tercatat.</h2><p className="muted small">{message}</p><Button onClick={()=>{setStep(0);setGeo(null);setDistance(null);setPhoto(null);setChallengeToken(null)}}>Selesai</Button></div>}
      {message&&step!==4&&<div className="callout warning" style={{marginTop:14}}>{message}</div>}
    </section>
    <aside className="card cardpad"><GeofenceMap office={office} user={geo}/><div className="list"><div className="listrow"><div><strong>{office.name}</strong><span>Pin kantor aktif · {workMode}</span></div><Badge tone="info">{office.radius} m radius</Badge></div><div className="listrow"><div><strong>Policy lokasi</strong><span>Accuracy maksimal {office.maxAccuracy} meter</span></div><Badge tone="success">Aktif</Badge></div><div className="listrow"><div><strong>Face evidence</strong><span>Provider adapter dapat dikonfigurasi</span></div><Badge tone={process.env.NEXT_PUBLIC_DEMO_MODE==="true"?"warning":"success"}>{demo?"Demo":"Enabled"}</Badge></div></div></aside>
  </div>;
}
